name: Publish to NPM

on:
    release:
        types: [created] # Trigger saat ada release baru

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm ci

            - name: Build package
              run: npm run build-npm:check # Build & cek apakah outputnya sesuai

            - name: Publish to NPM
              run: npm run build-npm:publish # Jalankan `npm publish --access public`
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
